date_format: '%F'
#date_format: '%F %R %Z'
godaddy:
  columns:
    index:
      title: '#'
      help: 'Approximate in which codes were added to this list.'
      type: index
    code:
      title: Code
      type: details-link
    expires:
      title: Expires
      help: 'Scheduled expiration date.  GoDaddy sometimes extends these.'
      type: timestamp
    oneuse:
      title: 'Reuse'
      help: 'Whether the code is reusable.  Non-reusable codes are limited to one use per user, credit card, and e-email.'
      type: boolean-good
      reverse: true
    regional:
      title: 'Regional'
      help: 'Regional codes may be restricted to certain countries or other regions.'
      type: boolean-bad
    mustfollowpath:
      title: 'Link Rqd'
      help: 'You may need a special link to use these codes.  Inquire on the forums for details.'
      type: boolean-bad
    newshopper:
      title: 'New Only'
      help: 'Typically only available to new users who have not yet purchased a product of the same type on GoDaddy.'
      type: boolean-bad
    type:
      title: Type
      help: 'Viral, order, or affiliate.'
      type: or-affiliate
    description:
      title: Description
      type: text
    usd:
      title: USD
      help: 'Works with currency: USD'
      type: contains-good
      searchfield: currencies
      value: USD
    aud:
      title: AUD
      help: 'Works with currency: AUD'
      type: contains-good
      searchfield: currencies
      value: AUD
    cad:
      title: CAD
      help: 'Works with currency: CAD'
      type: contains-good
      searchfield: currencies
      value: CAD
    iad:
      title: INR
      help: 'Works with currency: INR'
      type: contains-good
      searchfield: currencies
      value: INR
    gbp:
      title: GBP
      help: 'Works with currency: GBP'
      type: contains-good
      searchfield: currencies
      value: GBP
